repos:

# Quick content checks based on grepping for python specific patterns:
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.6.0
  hooks:
  - id: python-check-blanket-noqa   # Prohibit overly broad QA exclusions.
  - id: python-no-eval              # Never use eval() it's dangerous.
  - id: python-no-log-warn          # logger.warning(), not old .warn()

# Other file formatting, plus common Git mistakes & text file standardization:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files # Don't accidentally commit giant files.
  - id: check-merge-conflict    # Watch for lingering merge markers.
  - id: check-yaml              # Validate all YAML files.
  - id: check-case-conflict     # Avoid case sensitivity in file names.
  - id: debug-statements        # Watch for lingering debugger calls.
  - id: end-of-file-fixer       # Ensure there's a newline at EOF.
  - id: mixed-line-ending       # Only newlines, no line-feeds.
  - id: trailing-whitespace     # Remove trailing whitespace.
  - id: name-tests-test         # Follow PyTest naming convention.

# Attempt to enforce standardized PEP8 style formatting:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.4
  hooks:
  - id: autopep8

# Make sure import statements are sorted uniformly.
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.5.3
  hooks:
  - id: isort

# Check for PEP8 non-compliance, code complexity, and syntax errors:
# Make sure the following plugins are installed as well:
# - flake8-docstrings
# - flake8-rst-docstrings
# - flake8-builtins
# - pep8-naming
# - mccabe
- repo: https://github.com/PyCQA/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    args: [--config, .flake8]
    additional_dependencies:
      - flake8-docstrings
      - flake8-colors
      - pydocstyle
      - flake8-builtins
      - mccabe
      - naming
      - pycodestyle
      - pyflakes
      - flake8-rst-docstrings

# Check for errors in restructuredtext (.rst) files under the doc hierarchy
- repo: https://github.com/PyCQA/doc8
  rev: 0.9.0a1
  hooks:
  - id: doc8
    args: [--config, tox.ini]

# Check for known security vulnerabilities:
- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
  - id: bandit
    args: [--configfile, .bandit.yml]
