language: python
matrix:
  include:
  - python: '3.8'
    env: PY_VERSION=py38
    dist: xenial
addons:
  apt:
    packages:
    - libsnappy-dev
env:
  global:
  - secure: IAQoyAqW1pccRx1fqdnjJjh3iRe9l+rxU+OlQojvAqo4lcxdv6DkuVp4Rhvx2eiBXfdsZl7XrI2zCXHbVrUSbKL4RNnjv9ouJN/m29cUME+uwuTWOO+jY5g7bNdKOpeWvUZyhUR3FUdPdeh2sN7odsLF8XybV5uOdHdQSzK7R/Nf4XSYRgMsKLTNSq/MIBOD4goCpHT2etTe4P02HJxZ+a/ksv3DGI3cVgAcAzF8EDF0SFXauBZVYeffTl82lGSPRPVlUXdC7nBh8W9p49zJQEOhKq7rDMf5A3P8ZfoOVDBlsMGpqHJejezvR1c/GTDkenEWE8har4xwxvP/pJDfUrNKWjI79hdEpKcN2xOxAeobNAPJP4Ee33XCD6Q0spf7LePv3fNlERavqz0hNSIBrX4w2ueXBGh/hJr9fKtfDbcD7myRFe17X2vHEeiwzTGKkVVPqmaXRMg/1RgTHVFqhy2ayQpldvM+2d2Y9GO46CVr+Xf+CUdkOvNRd5tD9ur5s4L76GTJZlotGvZp0AIzgSa//wiX/ZGPTgN41NcDGnumbmfJ9nK11aCpq5elOaYunEKkiYzo1JSzNHxnoaa6lKLF3koRb7BUudHVxGsIUGMGTaXXjrMd1JF+RcISjija3YbzF//iheiTBJDbkl9TrMxVx0NFRG7SkG6jO0oHtcQ=
  - secure: D8kYR9AfTzH9eptRLy13E4g/gEtglXCEesZEJ6A6tj/Dcueq9D1K5BWXn7wCAVnJvMLj6PFTWHO8bMv2ol9Ukc6ZyxxVgCN1mzUFrhTRQs6pUdGvy5kgNqyAuVeFfF+CuYEwisFCv/9zLCacDbMcs/NLKa3RHHA5ELJaN0QzSedVRxukwAMPNqUuCPAu4V9XroGsRPEUwEwNvau84SU4a7PCHeoEGIWVu30cud4Qm5JOJmMAUbopsPeUTHy2HDWFPqjk9oTqaMG+cON+ki4kHMcob025CDY0ZrJ8S6Kq8a3zud2bleZZfok8JbLv8YGalXJgBBx9xnJRDp2eFkDOsTOWWNeZRMFkQCFNYNB6hCCRBrD9fPw0NPPCyU/uA6i+YoV3ynGyhSvVjEeIPvFKKAqpmbKqfEdbPRLQZYkJv0CnHYIxl/I0hgUhMPYQJmpfiE39qZ+CfmydtLmjFfl628uZqRaJDeq+IEunnEwGeZmCzv6ymexfxCC9RlxF+DMyTz6vn6PGBt/UMDlYPV/IRfXTE0MZAa0iyStsBHQRuqQ38x6h1QSRuS40F1e8Vq1Bv1/Orn6UH77Mwr4l1hjVcBYRQWrI/Y0y0vd8E0Lv9gEXd3Dw41Q3AE4HFeomaSCzX9wJ+eDu0TY9pZ1VDxHrUDnk3OzA7BW2dG94FFdmnN8=
git:
  depth: 1
branches:
  except:
  - docstrings-cleanup
before_install:
- df -h
- pwd
- ls -a
- uname -a
- git --version
- git tag
install:
- pip install tox
script:
- tox -v -e travis
after_success:
- "/usr/bin/curl -s https://codecov.io/bash -o codecov.sh"
- "/bin/bash codecov.sh"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/974b2fae96dbe33d3c65
    on_success: change
    on_failure: always
    on_start: never
  slack:
    secure: WuYtc2adpwG+EKxqIL2Hz1W8AL67/5HaILvQzEs7RM2+qUR+dvLroTdUl3nFTMYdvfaa6X+T4Loptjcpke3/0ZESynXegI3HL+KKOcDG6uoln6yEHM96WJ6uBjAR9Irkdx9NOBi1Py7SEDJ1LAOaxR1Z7re5UB6cZRQdCzsEIdcGmfb4aKAVLrowZiZmQKMlJXvd3LgSpGVhsCBV2msqBg0zz4ic5RYrCNNek/LN435sYgfzo2PN9wuVMarkR7plp925BVletqLcbL+0yrvLLxIAQrbWtF5vg0vlt8btps5PVf7DHkZYTBgjGHeayBcNGMgPHP3c4NAeU6t6VhwCY7rTHEI9HLwp8Qcd/pxLiDNq5csMz6yZ/1xmOreiHNAN48jxJefKGbeLUl9q9KLXuqrl+UuwEDJEcFFkpPKeCg0X2q3fk3mIighk0cfttAn42XXapd+TCplkwR7jiAnLr5S4F8nUpWirxCZeyO3YUS79RdtD1CZjdO/dB8bdzzp52puIq4GbkG8fVAQ5ZDGvWviEj5I194vylG0JQU5ohhDEM+alb8dc32euWbmsucjIiHH2Tr05UasLQbujEQaokVaHyBQEdSAvVyz1vScoKIJ4fxquGR0t5T0CbCvXumPxi8KmVK46oYo+23HJeHGIgzRD8XSoLsRW5DvnsXnQAdM=
