version: "3.8"
services:
  release:
    # TODO(rousik): this image is not public and may not match the code
    # but it may do the job for now.
    image: pudl-release:latest
    work_dir: /pudl/src
    volumes:
      - .:/pudl/src
      - build:/pudl/outputs
      - pudldata:/pudl/inputs/data
    command: >
      sh -c "ferc1_to_sqlite --sandbox release/settings.yml &&
             pudl_etl --sandbox release/settings.yml"
  # TODO(rousik): create validate service that validates stuff under build/
volumes:
  pudldata: {}
