name: pudl-test
channels:
  - conda-forge
  - defaults
  - intake
dependencies:
  - geopandas>=0.9,<11
  - numba~=0.53
  - pip~=21.0
  - pygeos>=0.10,<0.13
  - python-snappy>=0.6,<1
  - sqlite~=3.36
  - tox~=3.24
