name: pudl-dev
channels:
  - conda-forge
  - defaults
  - intake
dependencies:
  # Used to set up the environment
  - pip~=21.0
  - python>=3.8,<3.10
  # Package depending on binary libraries that need to be installed
  - geopandas~=0.9.0
  - libspatialite~=5.0  # SQLite extension for spatial data
  - numba~=0.53  # First numba version that's compatible with Python 3.9
  - pygeos~=0.9.0  # Python wrappers for the GEOS spatial libraries
  - python-graphviz~=0.16.0
  - python-snappy~=0.6.0
   # These are not normal Python packages available on PyPI
  - nodejs~=15.8  # Useful for Jupyter
  - pandoc~=2.11  # Useful for rendering RST files in Atom

  # Packages related to current projects but not the core package
  - dask~=2021.2 # For processing CEMS and eventually Prefect cloud ETL
  - pysal~=2.1 # Used for making maps in LBL / GridLab work
  - recordlinkage~=0.14.0 # Used for fuzzy merge between FERC/EIA for RMI

  # Jupyter notebook specific packages:
  - dask-labextension~=5.0
  - jupyter-resource-usage~=0.5.0
  - jupyterlab~=3.0

  # Use pip to install the main PUDL repo / package for development:
  - pip:
    - --editable ../[doc,test,dev]
