services:
  pudl-etl:
#   image: catalystcoop/pudl-etl:hello-docker
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - type: bind
        source: ${PUDL_IN}
        target: /home/catalyst/pudl_in
        consistency: delegated
      - type: bind
        source: ${PUDL_OUT}
        target: /home/catalyst/pudl_out
        consistency: delegated
    environment:
      - API_KEY_EIA
    container_name: pudl_etl
    command: cat /home/catalyst/.pudl.yml
