name: tox-pytest

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: cache-datastore
      with:
        path: ~/pudl-work/data/
        key: pudl-data-${{ hashFiles('**/datapackage.json') }}
        restore-keys: |
          pudl-data-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install libsnappy-dev
        python -m pip install --upgrade pip
        pip install tox

    - name: Check for cached data
      run: |
        mkdir -p ~/pudl-work/data/
        find ~/pudl-work/data/

    - name: Run PyTest with Tox
      env:
        API_KEY_EIA: ${{ secrets.API_KEY_EIA }}
      run: tox -ve scripts

    - name: Inspect Datastore
      run: find ~/pudl-work/data/

    - name: Upload test coverage report
      uses: codecov/codecov-action@v1

    - name: Archive test coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage.xml

    - name: Tell the Codemonkeys
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            username: 'action-slack',
            icon_emoji: ':octocat:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} succeeded in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ github.token }} # required
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
      if: always() # Pick up events even if the job fails or is canceled.
